"""create_sync_history_table

Revision ID: 1010afee8d9d
Revises: 7a3b4c5d6e7f
Create Date: 2026-06-24 16:10:41.384409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '1010afee8d9d'
down_revision: Union[str, Sequence[str], None] = '7a3b4c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum syncstatus safely
    sync_status_enum = sa.Enum('pending', 'running', 'completed', 'failed', name='syncstatus')
    sync_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('sync_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('problem_title', sa.String(length=255), nullable=False),
    sa.Column('problem_slug', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('repository_path', sa.Text(), nullable=True),
    sa.Column('commit_sha', sa.String(length=100), nullable=True),
    sa.Column('commit_url', sa.String(length=500), nullable=True),
    sa.Column('sync_status', ENUM(name='syncstatus', create_type=False), nullable=False),
    sa.Column('github_file_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'problem_slug', 'language', name='uq_sync_history_repo_slug_lang')
    )
    op.create_index(op.f('ix_sync_history_problem_slug'), 'sync_history', ['problem_slug'], unique=False)
    op.create_index(op.f('ix_sync_history_repository_id'), 'sync_history', ['repository_id'], unique=False)
    op.create_index(op.f('ix_sync_history_sync_status'), 'sync_history', ['sync_status'], unique=False)
    op.create_index(op.f('ix_sync_history_user_id'), 'sync_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_history_user_id'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_sync_status'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_repository_id'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_problem_slug'), table_name='sync_history')
    op.drop_table('sync_history')

    # Drop syncstatus enum safely
    sync_status_enum = sa.Enum('pending', 'running', 'completed', 'failed', name='syncstatus')
    sync_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
